// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjizoulxurkmiejilbqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqaXpvdWx4dXJrbWllamlsYnFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4ODY2MzEsImV4cCI6MjA3MTQ2MjYzMX0.kuydp3k_WU6Mso3BlMfIbtrgMyucpa06e9Hq74e_VMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});